### ISSUE TITLE
can not load pickle file

### ISSUE THREAD

**Issue by smallhaes** [yaqingwang/EANN-KDD18#2]
ModuleNotFoundError: No module named 'numpy.core.multiarray\r'
could you please list the modules such numpy and their versions using in this project ? thanks!

**Comment by topyun** [comment]
> ModuleNotFoundError: No module named 'numpy.core.multiarray\r'
> could you please list the modules such numpy and their versions using in this project ? thanks!

hi，the question I have encountered too，has this issue been fixed?

**Comment by smallhaes** [comment]
> > ModuleNotFoundError: No module named 'numpy.core.multiarray\r'
> > could you please list the modules such numpy and their versions using in this project ? thanks!
> 
> hi，the question I have encountered too，has this been fixed?
解决了, 这两个帖子也许有帮助~
https://blog.csdn.net/littlehaes/article/details/102644093
https://blog.csdn.net/littlehaes/article/details/102643890

**Comment by smallhaes** [comment]
> > ModuleNotFoundError: No module named 'numpy.core.multiarray\r'
> > could you please list the modules such numpy and their versions using in this project ? thanks!
> 
> hi，the question I have encountered too，has this been fixed?

错误原因: 这个pickle文件应该是在windows下用python2生成的, 我在linux下用python3跑就错了

**Comment by topyun** [comment]
> > > ModuleNotFoundError: No module named 'numpy.core.multiarray\r'
> > > could you please list the modules such numpy and their versions using in this project ? thanks!
> > 
> > 
> > hi，the question I have encountered too，has this been fixed?
> 
> 错误原因: 这个pickle文件应该是在windows下用python2生成的, 我在linux下用python3跑就错了

太感谢你了！（抱歉回复晚了），我是在windows下py3运行出错的，pickle文件按照你的办法解决了，但我应该需要再换个环境才能跑通

**Comment by skt-shreyas** [comment]
which python version are you using
