### ISSUE TITLE
there're no descriptions about pickle file

### ISSUE THREAD

**Issue by smallhaes** [yaqingwang/EANN-KDD18#3]
the .txt files are divided into training and test
the .pickle files are divided into training, validation, test
how to divide .txt and .pickle separately, is there any relation?

**Comment by wzhings** [comment]
Hi @smallhaes, I think you should first decide the settings of training, validation, and test (i.e. pickle files) and extract their image ids to save as pickles files. Then, you can use the image ids in certain folder to extract corresponding text content from .txt files. 
Hope my explanation helps.

**Comment by smallhaes** [comment]
> Hi @smallhaes, I think you should first decide the settings of training, validation, and test (i.e. pickle files) and extract their image ids to save as pickles files. Then, you can use the image ids in certain folder to extract corresponding text content from .txt files.
> Hope my explanation helps.

Thanks~
