### ISSUE TITLE
代码中只看到一个损失函数更新，哪里体现了对抗性？

### ISSUE THREAD

**Issue by beyondguo** [yaqingwang/EANN-KDD18#5]

**Comment by beyondguo** [comment]
我觉得应该是交替更新吧，您的论文中的算法也是这样写的，三个参数依次更新。

**Comment by beyondguo** [comment]
啊哈，不好意思，之前对domain-adaptation不了解，去看了一下相关的论文，才知道原来使用梯度翻转层来实现对抗。

**Comment by yaqingwang** [comment]
Yes, domain-adaption uses this trick to stabilize the training procedure.
